### ISSUE TITLE
setDataStorageURL signature is incorrect.

### ISSUE THREAD

**Issue by jianmingyong** [bowenwaregames/Vb.net-GJ-api#1]
data_URL += "&" & "signature=" & GJ_Signature
Return data_URL
End Function

I am sure it was a typo mistake in the last few lines causing it not to work. It should not be GJ_Signature.

**Comment by ttbowen** [comment]
what was the error? Sorry for the late reply as well.

**Comment by ttbowen** [comment]
I think I've solved it. One of the parameter names for "setDataStorageURL" was named "key", however it didn't occur to me at the time that "key" was a reserved keyword in VB.net. So a valid signature was not being generated, meaning the API call was invalid. I've fixed it up, and thanks for pointing it out.

**Comment by jianmingyong** [comment]
:) It is fixed.

**Comment by ttbowen** [comment]
That's good. You were correct as well, I was concatenating the wrong variable in the string for the API call. So thank you for pointing that out! =]
