### ISSUE TITLE
isLoggedIn always return false even if it is logged in.

### ISSUE THREAD

**Issue by jianmingyong** [bowenwaregames/Vb.net-GJ-api#2]
I have checked the codes once again and found out that GJ_isLoggedIn didn't set to true in any parts of the code. You might want to check again.

**Comment by ttbowen** [comment]
Yeah I think I've spotted the issue, it's simply because I forgot to set variable to check whether the user is logged in or not. I will fix that now. Also sorry for the lateness of my reply and thank you for bringing this to my attention.
